instance:
  clientUrl: https://fdp.tre.singou.net
  persistentUrl: https://fdp.tre.singou.net

repository:
    type: 5
    blazegraph:
        url: http://blazegraph:8080/blazegraph

ping:
    enabled: false
