services:
  nginx:
    image: nginx:1.29.4
    restart: unless-stopped
    networks:
      - tre-core
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh  # Script to autoreload Nginx when certs are renewed
      - ./nginx/confs_docker/:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      s3inbox:
        condition: service_started
      download:
        condition: service_started
      app:
        condition: service_started
      adele-website-frontend:
        condition: service_started
      adele-website-backend:
        condition: service_started
      fdp-client:
        condition: service_started

  certbot:
    image: certbot/certbot:v5.2.2
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      nginx:
        condition: service_started
    # Check validity and renew certificates every 15 hours    
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 15h & wait $${!}; done;'"


#networks:
  #tre-core:
      #external: true

